quote = "Думаю, на мировом рынке можно будет продать штук пять компьютеров."
print("Исходаня цитата:")
print(quote)
print("\nОна в верхнем регистре:")
print(quote.upper())
print("\nВ нижнем регистре:")
print(quote.lower())
print("\nКак загаловок:")
print(quote.title())
print("\nС ма-а-аленькой заменой:")
print(quote.replace("штук пять", "несколько миллионов"))
print("\nА вот опять исходная цитата:")
print(quote)
input("\n\nНажмите Enter, чтобы выйти.")