print("Открываю и закрываю файл.")
text_file = open("read_it.txt", "r", encoding='utf-8')
text_file.close()
print("\nЧитаю файл посимвольно.")
text_file = open("read_it.txt", "r")
print(text_file.read(1))
print(text_file.read(5))
text_file.close()

print("\nЧитаю файл целиком.")
open("read_it.txt", "r", encoding="utf-8")
whole_thing = text_file.read()
print(whole_thing)
text_file.close()

print("\nЧитаю одну строку посимвольно.")
text_file = open("read_it.txt", "r", encoding='utf-8')
print(text_file.readline(1))
print(text_file.readline(5))
text_file.close()
